### ISSUE TITLE
Published package on nuget.org is old

### ISSUE THREAD

**Issue by remixtedi** [pippinmole/BscScanner#1]
Please update the package on nuget.org, some methods are missing from version "0.1.0", for example, "GetTokenTotalSupply()".

**Comment by pippinmole** [comment]
Hello @remixtedi 

Thank you for your issue. I will be working on these endpoints, but as I do not have access to a PRO API key for BscScan, would you be able to provide the schemas for all PRO endpoints in order for me to create classes for these requests.

Look forward to hearing from you.

**Comment by remixtedi** [comment]
Hi @pippinmole ,
I am not talking about PRO endpoints, I mean your code in GitHub and the package that is available on nuget.org is not the same. You have all FREE endpoints in your repository (including schemas) but it is not packaged and published on nuget.org.

**Comment by pippinmole** [comment]
Hi @remixtedi 

Thanks for clarifying. Somehow I overlooked uploading a new nuget package for these changes. You should see the methods in [v0.1.1](https://www.nuget.org/packages/BscScanner/0.1.1).

Thanks again for bringing this to my attention.

**Comment by dhannyell** [comment]
Hello,

New parameters were added in some methods that are not present in v0.1.1 version.

could you please update the package?

**Comment by pippinmole** [comment]
Hi @dhannyell,

Would you be able to provide a list of methods that have changed parameters? I have installed v0.1.1 of the NuGet package, and compared it against the source code and I can't find any differences.

Looking forward to hearing from you

**Comment by dhannyell** [comment]
Hi @remixtedi 

GetErc721TokenTransfersByAddress()

in version 0.1.1 the constructor accepts only 1 parameter (address). On the main branch the constructor accepts 2 parameters (address and contractAddress)

**Comment by pippinmole** [comment]
I've pushed changes to NuGet, you can find it [here](https://www.nuget.org/packages/BscScanner).

Let me know if anything doesn't work 👍
